% compare distributions of initial sightings and simulated whales

% load simulated dataset
% positions generated by: [posx,posy] = CRW_fun(vals(1,:),vals(2,:),30*24*3600,2.5);
load('10w30dGoSL_positions')
%%
n = size(posx,2); % n whales

for j = 1:n
    hold on
    plot(posx(1,j),posy(1,j),'b.')
    plot(posx(:,j),posy(:,j))
end

% quicklook_whales
[Whale_count,A,longs,lats] = Whale_Count_GoSL_fun([num(:,4) num(:,3)]);

% reshape simulated positions 
allx = reshape(posx,length(posx)*n,1);
ally = reshape(posy,length(posy)*n,1);
[Whale_count_sim,A_sim] = Whale_Count_GoSL_fun([allx ally]);


GoSL_whales_fig 
figure(1),
contour(flipud(longs),lats,A_sim) 
print('10w30dGoSLcontours','-dpng')
%% 
close all, GoSL_whales_fig
figure(1), contour(flipud(longs),lats,A)
print('2017GoSLcontours','-dpng')

% one day
dsteps = (24*3600)/2.5; % how many steps in a day 

for j = 1:n
    hold on
    plot(posx(1,j),posy(1,j),'b.')
    plot(posx(1:dsteps,j),posy(1:dsteps,j))
end

% allx1d = reshape(posx(1:dsteps,:),dsteps*n,1);
% ally1d = reshape(posy(1:dsteps,:),dsteps*n,1);
% [Whale_count_sim,A_sim] = Whale_Count_GoSL_fun([allx1d ally1d]);
% 
% contour(flipud(longs),lats,A_sim)